### PR TITLE
add crosshair cursor position readout relative to a reference point

### PR DESCRIPTION
**Pull request by rudifa**
@pascalpp Hello Pascal, I have here a working proposal for a new feature: 
**crosshair cursor readout relative to a reference point set by the user**.

It works like this: 
- user moves the crosshair cursor to the desired reference point and taps on key "." to set it.
- henceforth the x, y readout values are relative to the reference point
- he (she?) can set a new reference point at any time
- the reference point remains active even if rulers are moved
- the reference point is cleared by cmd-R

Please let me know what do you think of this feature.

PS. While I removed my debug printouts from the commit, I left in my debugging tool `func printClassAndFunc`, which you might find useful for tracking function calls and data during test runs.
You just insert lines like these
```
       printClassAndFunc()
       printClassAndFunc(info: "mouseTickY=\(mouseTickY) label=\(label)")
```

@rudifa

### CODE REVIEW

**Comment by jeff-h** [comment]
This sounds really useful. I haven't tried your patch so am not sure of the details — does it adjust the zero point marked on the rulers to align with your mouse position when you press `.`?

Would it be possible to replace cmd-R with just a second press of `.`, to save remembering another keyboard shortcut?

**Comment by pascalpp** [comment]
I would expect a second press of `.` to set a new reference point, not to reset the reference point. But also I don't think we want to coupling this reset with cmd-R which resets the position of the rulers to some pretty arbitrary defaults. I think someone might want to carefully position the rulers on their screen and then move the zero point, and then reset the zero point to left and top without moving the rulers. So I think a separate command is warranted. Was thinking a good mnemonic would be for the reset cmd to be the same key combined with the cmd key, but then you'd end up with `cmd-period` which traditionally is another way to type `esc` (a convention dating back to early mac keyboards which didn't have a dedicated `esc` key). So let's mull this and see if we can find two key commands for `set zero point` and `reset zero point` that are easy to remember and don't conflict with existing keyboard conventions.

**Comment by rudifa** [comment]
Hello all,
I agree that cmr-R is not the best choice for resetting the reference point
back to windows origin. I took it just so that I can demonstrate the
feature. Any ideas are welcome.

Best regards
Rudi

PS to jeff-h: yes, pressing the "." sets the new origin (0,0) for (x,y)
cursor positions displayed on the rulers, so that you can easily measure
sizes of objects on screen.

**Comment by rudifa** [comment]
Replaced by a more recent PR **#104**

**Pull request closed without merging**
